CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password_hash BYTEA,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
